### PR TITLE
Stage Remake

### PR DESCRIPTION
**Pull request by GruelingPine185**
### Description

 
In an effort to rid the codebase of it's intricacy, this PR addresses the following issues:

- [x] Creating/modifying stages is not scalable or contributor friendly
- [ ] Excessive JS manipulation

## Todo

- [ ] Themes chosen on main page should carry over into game page or vice versa
- [ ] Remove all unnecessary code

## Solves

- #5
- #31

### CODE REVIEW

**Comment by devkennyy** [comment]
What were your plans on the excessive DOM manipulation? You could add jQuery to make DOM manipulation easier.

**Comment by GruelingPine185** [comment]
The the carrying over to other pages occurs with the old theme handling system on rungeon.live. The new theme system that I've been working on doesn't have this yet, so I made an issue to help me remember

**Comment by GruelingPine185** [comment]
I like vanilla Js and know it much better than jquery. If it helps you, you can convert the code to jquery because I can't. But just know that it's going to take me some time to familiarize myself with it

**Comment by devkennyy** [comment]
Would you like me to convert the code to jQuery within this pull request?

**Comment by GruelingPine185** [comment]
Go ahead and convert the code to jQuery. While your at it, could you help to resolve the issue where themes chosen on the main page doesn't get transferred to other pages?

**Comment by GruelingPine185** [comment]
I couldn't do much coding today, but I'll see what I can do about cleaning up the code over the coming days.

**Comment by devkennyy** [comment]
> While your at it, could you help to resolve the issue where themes chosen on the main page doesn't get transferred to other pages?

I can try :)

**Pull request merged**
