### PR TITLE
changed button text and visibility

### PR DESCRIPTION
**Pull request by staranbeer**
changed the continue button text and brightness

### CODE REVIEW

**Comment by GruelingPine185** [comment]
thank you for your contribution! It's appreciated :)

@devkennyy and myself are trying to resolve the theme issues #116. Because of the transformation to an _in development_ theme handling system, the `main` branch has some things that need to be addressed before we can safely continue.

**Comment by staranbeer** [comment]
sure! let me know if there is a way i can help with whatever you're currently working on. :wink:

**Comment by GruelingPine185** [comment]
@staranbeer So here is what I'd like for you to do. Do you mind updating your PR to conform to the changes on the `stage-remake` branch? This branch is the one with the new systems that will eventually replace the ones on the `main` branch. Since you are working with buttons, could you also style the buttons to look like the ones at https://rungeon.live/rungeon?

**Comment by staranbeer** [comment]
so instead of the code i edited on the main branch i should make a commit to the stage-remake branch with the changes? and by styling the buttons you mean add css to the buttons on the stage-remake branch? and if so shouldn't we just copy paste the styles from the main branch?

**Comment by GruelingPine185** [comment]
There are a few changes on the stage-remake branch that may affect the appearance of elements and therefore I wouldn't recommend copy/pasting changes from the main branch. To answer the first question, yes you could make a commit with the changes you made and revise them to fit with the already existing styles on the stage-remake branch.

**Pull request closed without merging**
