### PR TITLE
Coin and css fixes

### PR DESCRIPTION
**Pull request by PagliaraG**
### Description

Hi it's my first pull request on GitHub. I made the css leaner and also fixed the cursor on hover dragon

Closes #

### CODE REVIEW

**Comment by devkennyy** [comment]
Thanks so much, this definitely looks cleaner. We're currently in the process of migrating to Sass, and I hate to ask this but do you think you could do these same changes after I merge #19 ?

**Comment by PagliaraG** [comment]
Sure i can. I will be honest, is my first day on github , so can you explain how this merge will work?  Thank you so uch

**Comment by devkennyy** [comment]
Right, no problem. Are you familiar with Sass? I plan on migrating the source code to use Sass as opposed to CSS. Once I merge my changes, the source code will change and you can modify it from there. I hope you understand, if you like you can [join the Discord](https://discord.gg/SFX2KSuzep) to make communicating more efficient.

**Comment by devkennyy** [comment]
You can run `git fetch` to effectively update your code with the status of the repository. You are welcome to make your changes from there (I have merged #19)

**Comment by devkennyy** [comment]
#21

**Pull request closed without merging**
