### PR TITLE
Updated Linting-Formatting

### PR DESCRIPTION
**Pull request by JScrips**
### Description

I'm hoping that this provides an adequate solution to [#128 make ESLint format. ](https://github.com/devkennyy/rungeon/issues/128) 

In order to tackle this problem, I chose to integrate prettier and couple it with ESLint that is already present in the application. 
I also installed the ```eslint-config-prettier``` library to ensure that prettier and eslint work well together. I then made sure to add a new script ```npm run format``` that allows the developer to format all of the files within the application. I adjusted all potential errors so there shouldn't be any when running the format script. I made a small tweak to the ESLint rules in order to get it to stop yelling at everyone and coincide with prettier. 

## Changes

- added Prettier
- added prettierignore to mimic gitIgnore
- added prettierrc config file
- adjusted ESLint rules to cohabitate with Prettier
- added format script to run formatting for all files within application
-  proofread  rungeon.html,  files to delete / edit offending pieces of code that caused ESLint to yell 

## Solves

Closes [#128 ](https://github.com/devkennyy/rungeon/issues/128)

### CODE REVIEW

**Comment by GruelingPine185** [comment]
Hello @JScrips, we appreciate your contribution :). I'm looking at the changes within the commit and I noticed that semicolons and single quotes in `*.js` files were removed or replaced with double quotes respectively. The `.eslintrc.json` file states that the original functionality should take place. I also see there is a `.prettierrc.json` file which , so i'm guessing that this file has a higher precedence? and if I wanted to correct the changes to fit the preferred style, should I change both json files?

##### Forgive me I'm extremely new to the whole linting stuff

**Comment by JScrips** [comment]
@GruelingPine185 Hi! I'm super happy that I can help. I appreciate you guys allowing me the opportunity to. Also, please don't worry about it! There's nothing to forgive, navigating all of this is confusing and I _still_ have trouble nagivating today.  As far as taking care of the semicolons, that's an easy fix. if you go into the ```.prettierrc.json``` file and change line 2 where it says ```"semi" : false``` to ```"semi": true``` it will then add semicolons to the end of lines in *.js files. As far as precedence, I do believe that the ```prettierrc.json``` files has higher precedence when dealing with overlapping rules.  I have updated the prettierrc.json file so that semicolons will show up in *.js files.

I believe this precedence would be due to the adding of  ```eslint-config-prettier```

```
Turns off all rules that are unnecessary or might conflict with [Prettier](https://github.com/prettier/prettier).
```

here is a segment from their documentation [eslint-config-prettier]( https://github.com/prettier/eslint-config-prettier )
```
Extending "prettier" turns off a bunch of core ESLint rules, as well as a few rules from these plugins:

[@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint)
[@babel/eslint-plugin](https://github.com/babel/babel/tree/main/eslint/babel-eslint-plugin)
[eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel)
[eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype)
[eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)
[eslint-plugin-standard](https://github.com/xjamundx/eslint-plugin-standard)
[eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn)
[eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue)
👉 Using [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)? Check out [eslint-plugin-prettier’s recommended config](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration).

ℹ️ Note: You might find guides on the Internet saying you should also extend stuff like "prettier/react". Since version 8.0.0 of eslint-config-prettier, all you need to extend is "prettier"! That includes all plugins.
```

**Comment by GruelingPine185** [comment]
Thank you so much. I'll go ahead and resolve the conflicting files and wait for @devkennyy to do a review as well.

**Comment by devkennyy** [comment]
Do you mind updating the contributing guide by mentioning the new script?

**Comment by JScrips** [comment]
> Thank you so much. I'll go ahead and resolve the conflicting files and wait for @devkennyy to do a review as well.

It's my pleasure, if theres anything at all I could help with I"ll be sure to try my best to do so.

**Comment by JScrips** [comment]
> Do you mind updating the contributing guide by mentioning the new script? Everything else looks great! 🙃

Absolutely! I'll do that now!

**Review by devkennyy — APPROVED** [review]
Great work, thanks so much for contributing!

**Comment by JScrips** [comment]
> Great work, thanks so much for contributing!

My pleasure! It was a great experience. I've updated the contributor guide.

**Review by GruelingPine185 — APPROVED** [review]
Thx for your updated contribution. We are looking forward to seeing you here again :)

**Review by GruelingPine185 — COMMENTED** [review]
I hit the wrong button on accident... changes have been accepted and are being merged now

**Pull request merged**
