### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by Shabbyconnor**
### Description

Created a progress bar to display the progress through the stages

## Changes

* Added progress bar
* Added animation
* Added visibility toggle button

## To-Do

Fix the theme error?

### CODE REVIEW

**Comment by Shabbyconnor** [comment]
I clearly don't understand how rebasing works. I rebased twice and it still didn't do anything. Sigh. The last 5 commits are the rebase stuff. 

Before you merge can we figure out that error?
Screen Shot 2022-07-29 at 5 58 53 PM

**Comment by Shabbyconnor** [comment]
Okay. It's fixed 👍 Sorry that this is such a mess. I'm not good at the git side of things

**Comment by devkennyy** [comment]
No need to apologize, we're all learning 🙈

**Review by devkennyy — APPROVED** [review]
Very nice, thanks!

**Pull request merged**
